// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTidaaJsV0xDqgWn7rfhLvX9o07pu2EVw',
    appId: '1:710208049498:web:9a4f02e16f776bc2e92363',
    messagingSenderId: '710208049498',
    projectId: 'jaisawaljainparinay',
    authDomain: 'jaisawaljainparinay.firebaseapp.com',
    databaseURL: 'https://jaisawaljainparinay-default-rtdb.firebaseio.com',
    storageBucket: 'jaisawaljainparinay.appspot.com',
    measurementId: 'G-G9YLN4VY42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGwt3XsozkZyI_28tQ_KwdkA49gWg-wYw',
    appId: '1:710208049498:android:2e3c63d6ca96cc06e92363',
    messagingSenderId: '710208049498',
    projectId: 'jaisawaljainparinay',
    databaseURL: 'https://jaisawaljainparinay-default-rtdb.firebaseio.com',
    storageBucket: 'jaisawaljainparinay.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8S_KCakLsA1JfPuToArrzVecRanxtpME',
    appId: '1:710208049498:ios:c5f8516eefaa81d5e92363',
    messagingSenderId: '710208049498',
    projectId: 'jaisawaljainparinay',
    databaseURL: 'https://jaisawaljainparinay-default-rtdb.firebaseio.com',
    storageBucket: 'jaisawaljainparinay.appspot.com',
    iosBundleId: 'com.npr.aprjnew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8S_KCakLsA1JfPuToArrzVecRanxtpME',
    appId: '1:710208049498:ios:c5f8516eefaa81d5e92363',
    messagingSenderId: '710208049498',
    projectId: 'jaisawaljainparinay',
    databaseURL: 'https://jaisawaljainparinay-default-rtdb.firebaseio.com',
    storageBucket: 'jaisawaljainparinay.appspot.com',
    iosBundleId: 'com.npr.aprjnew',
  );
}
